#!/bin/bash
#SBATCH -A TG-SEE160002
#SBATCH -J test_mpi 
#SBATCH -o twotest.stdout
#SBATCH -N 2 -n 2
#SBATCH -p compute
#SBATCH --export=ALL
#SBATCH -t 00:30:00

#ibrun -n 1 ./graph_compute -nv 8 -c bfs -i 0 -d /oasis/projects/nsf/hmc104/schmidtd/web_data/test_verify 
ibrun -n 2 ./graph_compute -nv 5000000 -c bfs -i 2719708 -d /oasis/projects/nsf/hmc104/schmidtd/web_data/pld-arc
